sudo: true
language: node_js
env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: RjIzJh08PeIaqhLfOSTu00Jw6ih2fKzPdYZSK1/ol6JbU7+loWo+qjM4DQLPVRs1dgNG7klovlokXjoDvagTRbihTjfnstBVYigSzPgHv/NpV4g7CXW+BUBJZh3q+Tx0+Ly4VW8HU97fHX8gsrrH7pJFU+Qk9QyXsbAll4TT0pwGAlK3T46UN2LIuFVpdDx406ScU/GCYjXMAqxr76lr7oEeLvAm7x5LAgZ/ISq1hVLtKZEMyqiv2ZyzfD6hJWFn/hoA0SbjgfPWaZAwEyl4gdEgWmq0611mSVu2KN6UhXJQzf0AXdcZaQ07ototDvwkNuudxJV6YIqTREcWS+akHuez5QdkOE1iMqVeNHzMyni5/HV5lrGp+pHHLQq3RMlwJaqMKK2FwAt8m0Azzukr7fddfOLHbsSYItfg3xjlYjs+X7sGzGQ0bc/XLHiP9xTnLKT33jG3tGs6Mpzmrry7QvGrF1W3N7nRd8hKqoWSQwLIxCdyVrppgoWVUYWS3eSZ8JTQZBqt3SEGDgM6zIppzwP/LpX4W0BRvl33yIlhp0GnE2YwL5JkZMxW+Wce/bWbSdtdObGlL7PO4t67XwglYvYxvpI1301nCLoP1Zb5S9LZfvZ5nVpUT3Iu5xSC80Jos7ohFqsnd/4wFzYtomBwjNoeWE5uMJEsjfEEABNbbuA=
  # AWS_SECRET_ACCESS_KEY
  - secure: dgV41WLcx3YkHFzSKRYKGRzczTTnxm72pUiOH5U0fhrDLjnqTUBjMWnbTSrVz95m21/ZUj5NumtT8a5EFJklNdssPnB8BviIJlTPlQZgmdWhdCgZjfEvW3BfN9bRvY5nwFxHTktDE5yc8UAouPyhpYyGM0Uhy0zu85/pUMJXbo1f9ligSyAmaC8s+UFNSdpuyUwNRveA9QJyndyX26NHUT06X0UR1LKj+I5QHMyttmwgYHLRS+FPsOKSj5C5c778yJlZ5gdnT/eFaDbWq0GInsNaYi8dHYrnnghb6PdtPl3cCQG9cdEhT2x0R8JLWOBDywCXRPXmrRYqlME8+ohPxgJaNHXkyv2xLejSQZz06mYxvi1ZDyZrDpkoquw/+qZxbPRkRPt1mUDGibUsKnkyJO11zVGrZw+pZ/48WeL/UjcUwD6CyfQVdWHE8V2tyNfSbNXaGZNh0ZQImSwyXcKgHzzCZRmOiPEp3SmnahzjLaYclGYHftOY70cU7XNRi5PArPvsG9l7sg3QTgyIL1/Y/3tCv+o9MQsv/+1+Gd1dhI6DoftnNDVjnhKKj1ddM1E+HZelC6a5BA9bhBr6tKCxIpcMIOmOsTTZXshsrfN7grETykCFvk4s5HW4zPsMR3beJsHdx+1qcGddYPb2LqiwOFP3tvugoW2+dteXobiKZD8=
  branches:
  only:
  - master
services:
- docker
before_script:
- make ensure-dependencies
script:
- make brand
- make qa
deploy:
script: npm run deploy-dev
skip_cleanup: true
on:
  branch: master