sudo: true
language: node_js
env:
  global:
  # DOCKER_PASSWORD
  - secure: Olr4WygzPCKvfK5kujbxJeyuQ6FNoMaMCN6Ql8KcQk5+ubFskbAc9Qt8ew+9gLfNoGI+gG6W2PSf1RVoB9YKymOzPDwB0an3btTNnPqvZ6sWZVbl1zW2OH4lH7aZbnUpI02e7ByA48fQxxCC4PAbyDsptXtEvVOPV7MmZRW8CfZP7n7jGAbv3hYD0u5gIClhdVNk6AHTLXT7zVGHg7sGQjcZlqCpzDmpLdgV547+QzEfnTdSMYiSvbUoCHYh8vEabKYInW223G9T4mWlzrE/KmGqgrFZPaolL7ThwqjmxXxwy2BXuFyGpHGJzfl+0V5Z9gzMs0oiMdYhezVh/7MIT8PWa9Q6HQhMzbUN4K+TYyMOrccaH7ToymfJFzgTmSU+TQ+PdMdwu/0grP0ygUucwdpEyBB5h7aI+xLIAaajsO3qe+mT/IuqNm4pXNc1umVB8X91513T2TXeOHnU9Xd20qfXtHAs9VM5mz2w9HpuPugo9Jqm2XyKueug5mtIw/no2BB/H1cnULp66GYvK3oRnSbhOW83CqWK5eU5A+Tf8COkWqtxn61E/ri/4Ssuf3vFh2Tlxkdvj32t7e3TQNBJnNc1LXCDN9syONMy8LOXTN62nVxF2d48L2pfJBX8FMEKgY+ywhU1S/PVx48LQrvVQmQTLD/W0gcgpOQw4pfmtsA=
  # DOCKER_USERNAME
  - secure: Fe1uG2R3BAqup7bqmCXSjDkqGEUp2DpQFpE/XK7oHqyMd1pIU5BcnmTghG/b5O7gSM+sF+8Dd4kRnt5chID9gzBg/uOY+3d8mu9EH2ghJex5MJMex0Ze4NhFwjubEueH4TnaOqwJdmHg19WKZnwwvxKKhB7r/4jZz+HDpdqUtgAXi8PO1FaB4w2AHvrAKKDj8amN0Im6U1OvtXzAYXVSnph+JUf7g+K9cze+zj4prJVIll3fu5u2/HxJTFk9rts2fwdkbHNx3xJXCtfhyuhhbc++RMQ7oBZn8KFgkqFqdrtePtC6mQh+ynb1wf4Q8HakE09Po3hkkAJ93td6ZOjtbzqrDTS/fsWvhcGkSS6VWFedGImW0KGJxw9AUesZmJM8AhglolbTMicT/9mkyrI9QN/7dP5HeCjYBWNiAWSMNO5/+RPzrD0arIfZY19LrKTvHAswjGluA4zhSG1W+T/tDl0B5gfYMOYiRN8ja++MZc+eHAWKUryWAfcJJPSGiBXBA/W2xE/Ur3m4dcAjaDKRlPv+l2ZC893y7z6fYTIiV+fOmzsoB6TBWipvU/VKpL4LaPEhqCW/ta9jjGRPoA+tSHlxTUUzSI1kIh45i1tryly09gRElzwyQJjG6ooHkEQzBqq3ftFDp5rBAuDYCmZj5qXRlZKksCviiHECGYVeR4I=
branches:
  only:
  - master
services:
- docker
before_script:
- make ensure-dependencies
script:
- make brand
- make package
- make qa
- make archive
