service: guajirobot

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  iamRoleStatements:
   - Effect: "Allow"
     Action:
      - "s3:PutObject"
     Resource:
      Fn::Join:
        - ""
        - - Fn::GetAtt:
            - FilesBucket
            - Arn
          - "/*"
  environment:
    SERVICE_ENV: ${opt:stage, 'dev'}
    MONGO_URL: ${env:MONGO_URL}
    MONGO_DB: ${env:MONGO_DB}
    BOT_TOKEN: ${env:BOT_TOKEN}
    AIRTABLE_KEY: ${env:AIRTABLE_KEY}
    AIRTABLE_BASE: ${env:AIRTABLE_BASE}
custom:
  config:
    s3BucketName: "guajiros-files-${opt:stage, 'dev'}"
functions:
  process:
    handler: ./index.process
    events:
      - http:
          path: /guajirobot
          method: post
          cors: true
resources:
  Resources:
    FilesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.config.s3BucketName}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
              MaxAge: 3000

plugins:
  - serverless-dotenv-plugin