service: guajirobot

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  environment:
    SERVICE_ENV: ${opt:stage, 'dev'}

functions:
  process:
    handler: ./index.process
    events:
      - http:
          path: /guajirobot
          method: post
          cors: true